name:       'Fogies Base'
baseurl:    ''

brandimage: ''
brandtext:  'Fogies'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Sidebar-None'
      link: 'base_sample/bar-sidebar-none.html'
    - text: 'Sidebar-Right'
      link: 'base_sample/bar-sidebar-right.html'

exclude:
  # Bootstrap
  - bootstrap/less
  # CSS/LESS files, these are all included by css/base/styles.less
  - css/styles.less
  - css/base/bar.less
  - css/base/base.less
  - css/base/syntax.css
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env34
  - env35
  - requirements3.in
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests

#include:
#  # CSS/LESS files are included by this root
#  - css/base/styles.less
