name:       'DUB'

brandimage: 'images/nav_logo.png'
brandtext:  'DUB'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Home'
      link: 'index.html'
    - text: 'About DUB'
      link: 'aboutdub.html'
    - text: 'Calendar'
      link: 'calendar.html'
#    - text: 'People'
#      link: 'people.html'
#    - text: 'Resources'
#      link: 'resources.html'
    - text: 'Getting Involved'
      link: 'gettinginvolved.html'

collections:
  people:
    output: false
  seminars:
    output: true

defaults:
  - scope:
      type: people
    values:
      layout: person
  - scope:
      type: seminars
    values:
      layout: seminar
      archive: true

future: true

exclude:
  # Bootstrap
  - bootstrap/less
  # CSS/LESS files, these are all included by css/base/styles.less
  - css/styles.less
  - css/base/bar.less
  - css/base/base.less
  - css/base/syntax.css
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env34
  - env35
  - requirements3.in
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests
