name:       'Fogies Base'
baseurl:    ''

brandimage: ''
brandtext:  'Fogies'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Sidebar-None'
      link: 'base_sample/bar-sidebar-none.html'
    - text: 'Sidebar-Right'
      link: 'base_sample/bar-sidebar-right.html'

exclude:
  # Bootstrap
  - bootstrap/less
  # Node
  - node_modules
  # Python
  - env34
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests
